kind: Job
apiVersion: batch/v1
metadata:
  name: custom-stablediff
spec:
  template:
    spec:
      containers:
      - name: custom-stablediff
        image: "vebjornhal/cluster:diff_lib_test"
        workingDir: /storage/diffusion_lib_test
        command: ["sh", "custom_stablediff.sh"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0