kind: Job
apiVersion: batch/v1
metadata:
  name: img2img
spec:
  template:
    spec:
      containers:
      - name: img2img
        image: "vebjornhal/cluster:diff_lib_test_v1"
        workingDir: /storage/diffusion_lib_test
        command: ["sh", "super_res_img2img.sh"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0