kind: Job
apiVersion: batch/v1
metadata:
  name: super-res-inpainting
spec:
  template:
    spec:
      containers:
      - name: super-res-inpainting
        image: "vebjornhal/cluster:diff_lib_test"
        workingDir: /storage/diffusion_lib_test
        command: ["sh", "super_res_inpainting.sh"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0