kind: Job
apiVersion: batch/v1
metadata:
  name: text2img
spec:
  template:
    spec:
      containers:
      - name: text2img
        image: "vebjornhal/cluster:diff_lib_test2"
        workingDir: /storage/diffusion_lib_test
        command: ["sh", "stable-diff_init.sh"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0